# Test 
name: App Control

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: macos-latest

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GoogleService-Info.plist
        run: echo "$GOOGLE_SERVICE_INFO" > Medipills/GoogleService-Info.plist
        
      - name: Check Comfortaa.ttf permissions
        run: ls -l Medipills/Comfortaa.ttf
        
      - name: Create Comfortaa directory
        run: mkdir -p $HOME/work/Downloads/Comfortaa

      - name: Copy Comfortaa.ttf
        run: cp /Users/runner/Library/Developer/Xcode/DerivedData/Medipills-fcfyzvumkxvttzcpwnfwxeldqivu/Build/Products/Debug-iphonesimulator/Medipills.app/Comfortaa.ttf $HOME/work/Downloads/Comfortaa/Comfortaa.ttf
 
      - name: Create Downloads directory
        run: mkdir -p $HOME/work/Downloads

      - name: Copy JSON files
        run: |
         cp Medipills/Animations/syrup.json $HOME/work/Downloads/syrup.json
         cp Medipills/Animations/medicine.json $HOME/work/Downloads/medicine.json
         cp Medipills/Animations/blue_pill.json $HOME/work/Downloads/blue_pill.json

      - name: Copy GoogleService-Info.plist
        run: cp Medipills/GoogleService-Info.plist $HOME/work/Downloads/GoogleService-Info.plist

      - name: Clean project
        run: xcodebuild clean -scheme Medipills -project Medipills.xcodeproj

      - name: Build Medipills
        run: xcodebuild -scheme Medipills -project Medipills.xcodeproj -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" build

      - name: Run Unit Tests
        run: xcodebuild test -scheme Medipills -project Medipills.xcodeproj -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" clean build
