name: App Control

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GoogleService-Info.plist
        run: echo "$GOOGLE_SERVICE_INFO" > Medipills/GoogleService-Info.plist

      - name: Build Medipills
        run: xcodebuild -scheme Medipills -project Medipills.xcodeproj -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" build

      - name: Copy JSON files
        run: |
          cp Medipills/Animations/syrup.json $GITHUB_WORKSPACE/Downloads/syrup.json
          cp Medipills/Animations/medicine.json $GITHUB_WORKSPACE/Downloads/medicine.json
          cp Medipills/Animations/completing-tasks.json $GITHUB_WORKSPACE/Downloads/completing-tasks.json
          cp Medipills/Model/medic.json $GITHUB_WORKSPACE/Downloads/medic.json




      - name: Run Unit Tests
        run: xcodebuild test -scheme Medipills -project Medipills.xcodeproj -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" build
